### ISSUE TITLE
Zone doesn't get redrawn correctly

### ISSUE THREAD

**Issue by danidoedel** [citymania-org/cmclient#8] opened 2021-04-12 18:06 UTC
## Version of OpenTTD
1.11

## Expected result
Only the correct tiles should be colored

## Actual result
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/10995998/114440246-19ac9b80-9bf4-11eb-95b3-e90de80ece44.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10995998/114440342-321cb600-9bf4-11eb-8672-693ede999bac.png">

## Steps to reproduce
Activate the town growth tiles and let the city grow a bit, after a few tile changes the zoning gets messed up. Sometimes zooming out and in helps, sometimes only waiting for a bit helps. Switching zone off and on again doesn't help.

**Comment by ldpl** [comment] 2021-04-17 22:09
Can you please try to find a way to reproduce it more reliably and provide more details? I've never seen it like this and when I try to reproduce it as described it works perfectly fine.

**Comment by danidoedel** [comment] 2021-04-18 10:59
@ldpl Unfortunately it happens to me all the time so I can't find specific steps to trigger this :(
I'm on a MacBook Pro M1, maybe it's related to some graphics driver or something like that...




https://user-images.githubusercontent.com/10995998/115143040-25261980-a06f-11eb-8fe4-be4fe8dda621.mov


https://user-images.githubusercontent.com/10995998/115143081-68808800-a06f-11eb-9744-463cfaae1f79.mov


Sorry for the quality but I had to make it smaller otherwise I wouldn't be able to upload it here. But yeah I didn't do anything. Created a company, built the HQ, activated the zone and waited for the town to build something.

**Comment by danidoedel** [comment] 2021-04-18 11:01
Even on the title screen after leaving the game:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10995998/115143201-12f8ab00-a070-11eb-9d0d-79b974b2ef3c.png">

**Comment by ldpl** [comment] 2021-04-18 21:14
I couldn't reproduce it but I checked the code and found something that could be it. So I'm closing the bug but feel free to reopen it if 1.11.1 doesn't fix it.

**Closed by ldpl** 2021-04-18 21:14 UTC

**Comment by danidoedel** [comment] 2021-04-19 08:07
I did a quick test and it didn't occur so I assume that fixed it. Thanks! :)
